# Generated by Django 3.2.18 on 2023-03-10 11:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='activity_type',
            field=models.CharField(choices=[('Team Building Workshop', 'Team Building Workshop'), ('Carnival Team Challenge', 'Carnival Team Challenge'), ('Bridge Building Challeng', 'Bridge Building Challenge')], default='BBC', max_length=256, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 3, 12))], verbose_name='Booking date'),
        ),
    ]
